version: '3.7'

services:
    web:
        image: osmedeus:latest
        build:
            context: .
            dockerfile: Dockerfile
        # command: python3 /home/Osmedeus/server/manage.py runserver 0.0.0.0:8000
        ports:
            - "8180:8000"
        volumes:
            - osmedeusworkspaces:/root/.osmedeus/workspaces
        environment:
            DEBUG: 'false'
volumes:
    osmedeusworkspaces: